version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    environment:
      VITE_BACKEND_WS_URL: ws://localhost:8000/ws
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: bash -c "alembic upgrade head && poetry run server"
    ports:
      - 8000:8000
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      PG_URL: postgresql://postgres:password@db:5432/sidestacker
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sidestacker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
